### ISSUE TITLE
Ensure project runs locally on Desktop

### ISSUE THREAD

**Issue by maryjess** [maryjess/exSpent#25]
@le-cathelier to do:
* make sure git is on branch `cat`
* in a git bash terminal, type `git pull origin main`

how to ensure that project runs locally:
* ensure npm is there --> `npm`
* check npm version --> `npm -v`
* run `npm start` in git bash terminal

![image](https://github.com/user-attachments/assets/a78fbb07-5a2c-44e8-87c2-e4968825888a)
if this shows on your terminal, then its a success 🥳

**Comment by maryjess** [comment]
### how to stop the terminal from running?
Press `Ctrl+C` on your keyboard :>

**Comment by maryjess** [comment]
### so if i want to toggle between starting the thing and ending the thing?
Start: `npm start`
End: `Ctrl+C`

**Comment by le-cathelier** [comment]
> * ensure npm is there --> `npm`
> * check npm version --> `npm -v`

Attempting to install Node locally
https://treehouse.github.io/installation-guides/windows/node-windows.html#:~:text=Test%20NPM.,see%20something%20like%20this%201.4.

**Comment by le-cathelier** [comment]
done

**Comment by maryjess** [comment]
Should be working on all locals
